application: web592group23
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /(.*\.(js|css|html|gif|png|jpg|wav|mp3|json|atlas|map|min|woff|woff2|eot))$
  static_files: \1
  upload: .*\.(js|css|html|gif|png|jpg|wav|mp3|json|atlas|map|min|woff|woff2|eot)$

- url: /(.*\.php)$
  script: \1

- url: /
  script: index.php
